version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2023.11.0
    restart: unless-stopped
    network_mode: "host"
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8081:8081/tcp"
    volumes:
      - "./etc-pihole:/etc/pihole:rw"
      - "./etc-dnsmasq.d:/etc/dnsmasq.d:rw"
    environment:
      - DNSMASQ_LISTENING=all
      - WEBPASSWORD=123
      - WEB_PORT=8081
