---
- name: Deploy Pihole & DNS
  hosts: arkstar
  become: true
  tasks:
    - name: "Set service name"
      set_fact:
        service_name: "pihole-and-dns"
        root_domain: "arkstar.dev"
        dns_domain: "dns.arkstar.dev"
        unifi_domain: "unifi.arkstar.dev"
        observability_domain: "observability.arkstar.dev"
        jellyfin_domain: "jellyfin.arkstar.dev"
        nas_domain: "nas.arkstar.dev"
        photo_domain: "photo.arkstar.dev"
        prox_domain: "prox.arkstar.dev"

    - name: Setup service
      ansible.builtin.import_tasks:
        file: "../../ansible/tasks/setup_service.yml"

    - name: Use PiHole DNS on host
      lineinfile:
        dest: /etc/resolv.conf
        line: "nameserver 127.0.0.1"
        mode: "0644"

    - name: "Set up local DNS: {{ root_domain }}"
      lineinfile:
        dest: "{{ remote_service_dir }}/etc-pihole/custom.list"
        line: "{{ ansible_default_ipv4.address }} {{ root_domain }}"
        mode: "0644"
        create: true

    - name: "Set up local DNS: {{ dns_domain }}"
      lineinfile:
        dest: "{{ remote_service_dir }}/etc-pihole/custom.list"
        line: "{{ ansible_default_ipv4.address }} {{ dns_domain }}"
        mode: "0644"
        create: true

   
    - name: "Set up local DNS: {{ unifi_domain }}"
      lineinfile:
        dest: "{{ remote_service_dir }}/etc-pihole/custom.list"
        line: "{{ ansible_default_ipv4.address }} {{ unifi_domain }}"
        mode: "0644"
        create: true

    - name: "Set up local DNS: {{ observability_domain }}"
      lineinfile:
        dest: "{{ remote_service_dir }}/etc-pihole/custom.list"
        line: "{{ ansible_default_ipv4.address }} {{ observability_domain }}"
        mode: "0644"
        create: true

    - name: "Set up local DNS: {{ jellyfin_domain }}"
      lineinfile:
        dest: "{{ remote_service_dir }}/etc-pihole/custom.list"
        line: "{{ ansible_default_ipv4.address }} {{ jellyfin_domain }}"
        mode: "0644"
        create: true

    - name: "Set up local DNS: {{ nas_domain }}"
      lineinfile:
        dest: "{{ remote_service_dir }}/etc-pihole/custom.list"
        line: "{{ ansible_default_ipv4.address }} {{ nas_domain }}"
        mode: "0644"
        create: true

    - name: "Set up local DNS: {{ photo_domain }}"
      lineinfile:
        dest: "{{ remote_service_dir }}/etc-pihole/custom.list"
        line: "{{ ansible_default_ipv4.address }} {{ photo_domain }}"
        mode: "0644"
        create: true
    
    - name: "Set up local DNS: {{ prox_domain }}"
      lineinfile:
        dest: "{{ remote_service_dir }}/etc-pihole/custom.list"
        line: "{{ ansible_default_ipv4.address }} {{ prox_domain }}"
        mode: "0644"
        create: true


    - name: Restart service
      shell: |
        docker compose -f {{ remote_service_dir }}/docker-compose.yml restart 
      args:
        chdir: "{{ remote_service_dir }}"


