---
- name: Deploy immich
  hosts: arkstar
  become: true
  tasks:
    - name: "Set service name"
      set_fact:
        service_name: "immich"

    - name: Setup service
      ansible.builtin.import_tasks:
        file: "../../ansible/tasks/setup_service.yml"
